/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InterestsRouteRouteImport } from './routes/interests/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InterestsIndexRouteImport } from './routes/interests/index'
import { Route as InterestsCreateRouteImport } from './routes/interests/create'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLogoutRouteImport } from './routes/(auth)/logout'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authAccountRouteImport } from './routes/(auth)/account'
import { Route as InterestsIdRouteRouteImport } from './routes/interests/$id/route'
import { Route as InterestsIdIndexRouteImport } from './routes/interests/$id/index'
import { Route as InterestsIdEditRouteImport } from './routes/interests/$id/edit'

const InterestsRouteRoute = InterestsRouteRouteImport.update({
  id: '/interests',
  path: '/interests',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsIndexRoute = InterestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InterestsRouteRoute,
} as any)
const InterestsCreateRoute = InterestsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => InterestsRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLogoutRoute = authLogoutRouteImport.update({
  id: '/(auth)/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authAccountRoute = authAccountRouteImport.update({
  id: '/(auth)/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsIdRouteRoute = InterestsIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InterestsRouteRoute,
} as any)
const InterestsIdIndexRoute = InterestsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InterestsIdRouteRoute,
} as any)
const InterestsIdEditRoute = InterestsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => InterestsIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/interests': typeof InterestsRouteRouteWithChildren
  '/interests/$id': typeof InterestsIdRouteRouteWithChildren
  '/account': typeof authAccountRoute
  '/login': typeof authLoginRoute
  '/logout': typeof authLogoutRoute
  '/register': typeof authRegisterRoute
  '/interests/create': typeof InterestsCreateRoute
  '/interests/': typeof InterestsIndexRoute
  '/interests/$id/edit': typeof InterestsIdEditRoute
  '/interests/$id/': typeof InterestsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof authAccountRoute
  '/login': typeof authLoginRoute
  '/logout': typeof authLogoutRoute
  '/register': typeof authRegisterRoute
  '/interests/create': typeof InterestsCreateRoute
  '/interests': typeof InterestsIndexRoute
  '/interests/$id/edit': typeof InterestsIdEditRoute
  '/interests/$id': typeof InterestsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/interests': typeof InterestsRouteRouteWithChildren
  '/interests/$id': typeof InterestsIdRouteRouteWithChildren
  '/(auth)/account': typeof authAccountRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/logout': typeof authLogoutRoute
  '/(auth)/register': typeof authRegisterRoute
  '/interests/create': typeof InterestsCreateRoute
  '/interests/': typeof InterestsIndexRoute
  '/interests/$id/edit': typeof InterestsIdEditRoute
  '/interests/$id/': typeof InterestsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/interests'
    | '/interests/$id'
    | '/account'
    | '/login'
    | '/logout'
    | '/register'
    | '/interests/create'
    | '/interests/'
    | '/interests/$id/edit'
    | '/interests/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/logout'
    | '/register'
    | '/interests/create'
    | '/interests'
    | '/interests/$id/edit'
    | '/interests/$id'
  id:
    | '__root__'
    | '/'
    | '/interests'
    | '/interests/$id'
    | '/(auth)/account'
    | '/(auth)/login'
    | '/(auth)/logout'
    | '/(auth)/register'
    | '/interests/create'
    | '/interests/'
    | '/interests/$id/edit'
    | '/interests/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InterestsRouteRoute: typeof InterestsRouteRouteWithChildren
  authAccountRoute: typeof authAccountRoute
  authLoginRoute: typeof authLoginRoute
  authLogoutRoute: typeof authLogoutRoute
  authRegisterRoute: typeof authRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/interests': {
      id: '/interests'
      path: '/interests'
      fullPath: '/interests'
      preLoaderRoute: typeof InterestsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests/': {
      id: '/interests/'
      path: '/'
      fullPath: '/interests/'
      preLoaderRoute: typeof InterestsIndexRouteImport
      parentRoute: typeof InterestsRouteRoute
    }
    '/interests/create': {
      id: '/interests/create'
      path: '/create'
      fullPath: '/interests/create'
      preLoaderRoute: typeof InterestsCreateRouteImport
      parentRoute: typeof InterestsRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/logout': {
      id: '/(auth)/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof authLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/account': {
      id: '/(auth)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof authAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests/$id': {
      id: '/interests/$id'
      path: '/$id'
      fullPath: '/interests/$id'
      preLoaderRoute: typeof InterestsIdRouteRouteImport
      parentRoute: typeof InterestsRouteRoute
    }
    '/interests/$id/': {
      id: '/interests/$id/'
      path: '/'
      fullPath: '/interests/$id/'
      preLoaderRoute: typeof InterestsIdIndexRouteImport
      parentRoute: typeof InterestsIdRouteRoute
    }
    '/interests/$id/edit': {
      id: '/interests/$id/edit'
      path: '/edit'
      fullPath: '/interests/$id/edit'
      preLoaderRoute: typeof InterestsIdEditRouteImport
      parentRoute: typeof InterestsIdRouteRoute
    }
  }
}

interface InterestsIdRouteRouteChildren {
  InterestsIdEditRoute: typeof InterestsIdEditRoute
  InterestsIdIndexRoute: typeof InterestsIdIndexRoute
}

const InterestsIdRouteRouteChildren: InterestsIdRouteRouteChildren = {
  InterestsIdEditRoute: InterestsIdEditRoute,
  InterestsIdIndexRoute: InterestsIdIndexRoute,
}

const InterestsIdRouteRouteWithChildren =
  InterestsIdRouteRoute._addFileChildren(InterestsIdRouteRouteChildren)

interface InterestsRouteRouteChildren {
  InterestsIdRouteRoute: typeof InterestsIdRouteRouteWithChildren
  InterestsCreateRoute: typeof InterestsCreateRoute
  InterestsIndexRoute: typeof InterestsIndexRoute
}

const InterestsRouteRouteChildren: InterestsRouteRouteChildren = {
  InterestsIdRouteRoute: InterestsIdRouteRouteWithChildren,
  InterestsCreateRoute: InterestsCreateRoute,
  InterestsIndexRoute: InterestsIndexRoute,
}

const InterestsRouteRouteWithChildren = InterestsRouteRoute._addFileChildren(
  InterestsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InterestsRouteRoute: InterestsRouteRouteWithChildren,
  authAccountRoute: authAccountRoute,
  authLoginRoute: authLoginRoute,
  authLogoutRoute: authLogoutRoute,
  authRegisterRoute: authRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
