/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartnerRouteRouteImport } from './routes/partner/route'
import { Route as InterestsRouteRouteImport } from './routes/interests/route'
import { Route as ConversationStartersRouteRouteImport } from './routes/conversation-starters/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnerIndexRouteImport } from './routes/partner/index'
import { Route as InterestsIndexRouteImport } from './routes/interests/index'
import { Route as ConversationStartersIndexRouteImport } from './routes/conversation-starters/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as InterestsCreateRouteImport } from './routes/interests/create'
import { Route as ConversationStartersCreateRouteImport } from './routes/conversation-starters/create'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLogoutRouteImport } from './routes/(auth)/logout'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authAccountRouteImport } from './routes/(auth)/account'
import { Route as InterestsIdRouteRouteImport } from './routes/interests/$id/route'
import { Route as ConversationStartersIdRouteRouteImport } from './routes/conversation-starters/$id/route'
import { Route as InterestsIdIndexRouteImport } from './routes/interests/$id/index'
import { Route as ConversationStartersIdIndexRouteImport } from './routes/conversation-starters/$id/index'
import { Route as PartnerDealsCreateRouteImport } from './routes/partner/deals/create'
import { Route as InterestsIdEditRouteImport } from './routes/interests/$id/edit'
import { Route as ConversationStartersIdEditRouteImport } from './routes/conversation-starters/$id/edit'
import { Route as PartnerVenueVenueIdEditRouteImport } from './routes/partner/venue/$venueId/edit'
import { Route as PartnerDealsDealIdEditRouteImport } from './routes/partner/deals/$dealId/edit'
import { Route as InterestsIdConversationStartersCreateRouteImport } from './routes/interests/$id/conversation-starters/create'
import { Route as InterestsIdConversationStartersStarterIdRouteRouteImport } from './routes/interests/$id/conversation-starters/$starterId/route'
import { Route as InterestsIdConversationStartersStarterIdIndexRouteImport } from './routes/interests/$id/conversation-starters/$starterId/index'
import { Route as InterestsIdConversationStartersStarterIdEditRouteImport } from './routes/interests/$id/conversation-starters/$starterId/edit'

const PartnerRouteRoute = PartnerRouteRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsRouteRoute = InterestsRouteRouteImport.update({
  id: '/interests',
  path: '/interests',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationStartersRouteRoute =
  ConversationStartersRouteRouteImport.update({
    id: '/conversation-starters',
    path: '/conversation-starters',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const InterestsIndexRoute = InterestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InterestsRouteRoute,
} as any)
const ConversationStartersIndexRoute =
  ConversationStartersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConversationStartersRouteRoute,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const InterestsCreateRoute = InterestsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => InterestsRouteRoute,
} as any)
const ConversationStartersCreateRoute =
  ConversationStartersCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => ConversationStartersRouteRoute,
  } as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLogoutRoute = authLogoutRouteImport.update({
  id: '/(auth)/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authAccountRoute = authAccountRouteImport.update({
  id: '/(auth)/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsIdRouteRoute = InterestsIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InterestsRouteRoute,
} as any)
const ConversationStartersIdRouteRoute =
  ConversationStartersIdRouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ConversationStartersRouteRoute,
  } as any)
const InterestsIdIndexRoute = InterestsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InterestsIdRouteRoute,
} as any)
const ConversationStartersIdIndexRoute =
  ConversationStartersIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConversationStartersIdRouteRoute,
  } as any)
const PartnerDealsCreateRoute = PartnerDealsCreateRouteImport.update({
  id: '/deals/create',
  path: '/deals/create',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const InterestsIdEditRoute = InterestsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => InterestsIdRouteRoute,
} as any)
const ConversationStartersIdEditRoute =
  ConversationStartersIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ConversationStartersIdRouteRoute,
  } as any)
const PartnerVenueVenueIdEditRoute = PartnerVenueVenueIdEditRouteImport.update({
  id: '/venue/$venueId/edit',
  path: '/venue/$venueId/edit',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const PartnerDealsDealIdEditRoute = PartnerDealsDealIdEditRouteImport.update({
  id: '/deals/$dealId/edit',
  path: '/deals/$dealId/edit',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const InterestsIdConversationStartersCreateRoute =
  InterestsIdConversationStartersCreateRouteImport.update({
    id: '/conversation-starters/create',
    path: '/conversation-starters/create',
    getParentRoute: () => InterestsIdRouteRoute,
  } as any)
const InterestsIdConversationStartersStarterIdRouteRoute =
  InterestsIdConversationStartersStarterIdRouteRouteImport.update({
    id: '/conversation-starters/$starterId',
    path: '/conversation-starters/$starterId',
    getParentRoute: () => InterestsIdRouteRoute,
  } as any)
const InterestsIdConversationStartersStarterIdIndexRoute =
  InterestsIdConversationStartersStarterIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => InterestsIdConversationStartersStarterIdRouteRoute,
  } as any)
const InterestsIdConversationStartersStarterIdEditRoute =
  InterestsIdConversationStartersStarterIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => InterestsIdConversationStartersStarterIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/conversation-starters': typeof ConversationStartersRouteRouteWithChildren
  '/interests': typeof InterestsRouteRouteWithChildren
  '/partner': typeof PartnerRouteRouteWithChildren
  '/conversation-starters/$id': typeof ConversationStartersIdRouteRouteWithChildren
  '/interests/$id': typeof InterestsIdRouteRouteWithChildren
  '/account': typeof authAccountRoute
  '/login': typeof authLoginRoute
  '/logout': typeof authLogoutRoute
  '/register': typeof authRegisterRoute
  '/conversation-starters/create': typeof ConversationStartersCreateRoute
  '/interests/create': typeof InterestsCreateRoute
  '/admin/': typeof AdminIndexRoute
  '/conversation-starters/': typeof ConversationStartersIndexRoute
  '/interests/': typeof InterestsIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/conversation-starters/$id/edit': typeof ConversationStartersIdEditRoute
  '/interests/$id/edit': typeof InterestsIdEditRoute
  '/partner/deals/create': typeof PartnerDealsCreateRoute
  '/conversation-starters/$id/': typeof ConversationStartersIdIndexRoute
  '/interests/$id/': typeof InterestsIdIndexRoute
  '/interests/$id/conversation-starters/$starterId': typeof InterestsIdConversationStartersStarterIdRouteRouteWithChildren
  '/interests/$id/conversation-starters/create': typeof InterestsIdConversationStartersCreateRoute
  '/partner/deals/$dealId/edit': typeof PartnerDealsDealIdEditRoute
  '/partner/venue/$venueId/edit': typeof PartnerVenueVenueIdEditRoute
  '/interests/$id/conversation-starters/$starterId/edit': typeof InterestsIdConversationStartersStarterIdEditRoute
  '/interests/$id/conversation-starters/$starterId/': typeof InterestsIdConversationStartersStarterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof authAccountRoute
  '/login': typeof authLoginRoute
  '/logout': typeof authLogoutRoute
  '/register': typeof authRegisterRoute
  '/conversation-starters/create': typeof ConversationStartersCreateRoute
  '/interests/create': typeof InterestsCreateRoute
  '/admin': typeof AdminIndexRoute
  '/conversation-starters': typeof ConversationStartersIndexRoute
  '/interests': typeof InterestsIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/conversation-starters/$id/edit': typeof ConversationStartersIdEditRoute
  '/interests/$id/edit': typeof InterestsIdEditRoute
  '/partner/deals/create': typeof PartnerDealsCreateRoute
  '/conversation-starters/$id': typeof ConversationStartersIdIndexRoute
  '/interests/$id': typeof InterestsIdIndexRoute
  '/interests/$id/conversation-starters/create': typeof InterestsIdConversationStartersCreateRoute
  '/partner/deals/$dealId/edit': typeof PartnerDealsDealIdEditRoute
  '/partner/venue/$venueId/edit': typeof PartnerVenueVenueIdEditRoute
  '/interests/$id/conversation-starters/$starterId/edit': typeof InterestsIdConversationStartersStarterIdEditRoute
  '/interests/$id/conversation-starters/$starterId': typeof InterestsIdConversationStartersStarterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/conversation-starters': typeof ConversationStartersRouteRouteWithChildren
  '/interests': typeof InterestsRouteRouteWithChildren
  '/partner': typeof PartnerRouteRouteWithChildren
  '/conversation-starters/$id': typeof ConversationStartersIdRouteRouteWithChildren
  '/interests/$id': typeof InterestsIdRouteRouteWithChildren
  '/(auth)/account': typeof authAccountRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/logout': typeof authLogoutRoute
  '/(auth)/register': typeof authRegisterRoute
  '/conversation-starters/create': typeof ConversationStartersCreateRoute
  '/interests/create': typeof InterestsCreateRoute
  '/admin/': typeof AdminIndexRoute
  '/conversation-starters/': typeof ConversationStartersIndexRoute
  '/interests/': typeof InterestsIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/conversation-starters/$id/edit': typeof ConversationStartersIdEditRoute
  '/interests/$id/edit': typeof InterestsIdEditRoute
  '/partner/deals/create': typeof PartnerDealsCreateRoute
  '/conversation-starters/$id/': typeof ConversationStartersIdIndexRoute
  '/interests/$id/': typeof InterestsIdIndexRoute
  '/interests/$id/conversation-starters/$starterId': typeof InterestsIdConversationStartersStarterIdRouteRouteWithChildren
  '/interests/$id/conversation-starters/create': typeof InterestsIdConversationStartersCreateRoute
  '/partner/deals/$dealId/edit': typeof PartnerDealsDealIdEditRoute
  '/partner/venue/$venueId/edit': typeof PartnerVenueVenueIdEditRoute
  '/interests/$id/conversation-starters/$starterId/edit': typeof InterestsIdConversationStartersStarterIdEditRoute
  '/interests/$id/conversation-starters/$starterId/': typeof InterestsIdConversationStartersStarterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/conversation-starters'
    | '/interests'
    | '/partner'
    | '/conversation-starters/$id'
    | '/interests/$id'
    | '/account'
    | '/login'
    | '/logout'
    | '/register'
    | '/conversation-starters/create'
    | '/interests/create'
    | '/admin/'
    | '/conversation-starters/'
    | '/interests/'
    | '/partner/'
    | '/conversation-starters/$id/edit'
    | '/interests/$id/edit'
    | '/partner/deals/create'
    | '/conversation-starters/$id/'
    | '/interests/$id/'
    | '/interests/$id/conversation-starters/$starterId'
    | '/interests/$id/conversation-starters/create'
    | '/partner/deals/$dealId/edit'
    | '/partner/venue/$venueId/edit'
    | '/interests/$id/conversation-starters/$starterId/edit'
    | '/interests/$id/conversation-starters/$starterId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/logout'
    | '/register'
    | '/conversation-starters/create'
    | '/interests/create'
    | '/admin'
    | '/conversation-starters'
    | '/interests'
    | '/partner'
    | '/conversation-starters/$id/edit'
    | '/interests/$id/edit'
    | '/partner/deals/create'
    | '/conversation-starters/$id'
    | '/interests/$id'
    | '/interests/$id/conversation-starters/create'
    | '/partner/deals/$dealId/edit'
    | '/partner/venue/$venueId/edit'
    | '/interests/$id/conversation-starters/$starterId/edit'
    | '/interests/$id/conversation-starters/$starterId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/conversation-starters'
    | '/interests'
    | '/partner'
    | '/conversation-starters/$id'
    | '/interests/$id'
    | '/(auth)/account'
    | '/(auth)/login'
    | '/(auth)/logout'
    | '/(auth)/register'
    | '/conversation-starters/create'
    | '/interests/create'
    | '/admin/'
    | '/conversation-starters/'
    | '/interests/'
    | '/partner/'
    | '/conversation-starters/$id/edit'
    | '/interests/$id/edit'
    | '/partner/deals/create'
    | '/conversation-starters/$id/'
    | '/interests/$id/'
    | '/interests/$id/conversation-starters/$starterId'
    | '/interests/$id/conversation-starters/create'
    | '/partner/deals/$dealId/edit'
    | '/partner/venue/$venueId/edit'
    | '/interests/$id/conversation-starters/$starterId/edit'
    | '/interests/$id/conversation-starters/$starterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ConversationStartersRouteRoute: typeof ConversationStartersRouteRouteWithChildren
  InterestsRouteRoute: typeof InterestsRouteRouteWithChildren
  PartnerRouteRoute: typeof PartnerRouteRouteWithChildren
  authAccountRoute: typeof authAccountRoute
  authLoginRoute: typeof authLoginRoute
  authLogoutRoute: typeof authLogoutRoute
  authRegisterRoute: typeof authRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests': {
      id: '/interests'
      path: '/interests'
      fullPath: '/interests'
      preLoaderRoute: typeof InterestsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation-starters': {
      id: '/conversation-starters'
      path: '/conversation-starters'
      fullPath: '/conversation-starters'
      preLoaderRoute: typeof ConversationStartersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/interests/': {
      id: '/interests/'
      path: '/'
      fullPath: '/interests/'
      preLoaderRoute: typeof InterestsIndexRouteImport
      parentRoute: typeof InterestsRouteRoute
    }
    '/conversation-starters/': {
      id: '/conversation-starters/'
      path: '/'
      fullPath: '/conversation-starters/'
      preLoaderRoute: typeof ConversationStartersIndexRouteImport
      parentRoute: typeof ConversationStartersRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/interests/create': {
      id: '/interests/create'
      path: '/create'
      fullPath: '/interests/create'
      preLoaderRoute: typeof InterestsCreateRouteImport
      parentRoute: typeof InterestsRouteRoute
    }
    '/conversation-starters/create': {
      id: '/conversation-starters/create'
      path: '/create'
      fullPath: '/conversation-starters/create'
      preLoaderRoute: typeof ConversationStartersCreateRouteImport
      parentRoute: typeof ConversationStartersRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/logout': {
      id: '/(auth)/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof authLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/account': {
      id: '/(auth)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof authAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests/$id': {
      id: '/interests/$id'
      path: '/$id'
      fullPath: '/interests/$id'
      preLoaderRoute: typeof InterestsIdRouteRouteImport
      parentRoute: typeof InterestsRouteRoute
    }
    '/conversation-starters/$id': {
      id: '/conversation-starters/$id'
      path: '/$id'
      fullPath: '/conversation-starters/$id'
      preLoaderRoute: typeof ConversationStartersIdRouteRouteImport
      parentRoute: typeof ConversationStartersRouteRoute
    }
    '/interests/$id/': {
      id: '/interests/$id/'
      path: '/'
      fullPath: '/interests/$id/'
      preLoaderRoute: typeof InterestsIdIndexRouteImport
      parentRoute: typeof InterestsIdRouteRoute
    }
    '/conversation-starters/$id/': {
      id: '/conversation-starters/$id/'
      path: '/'
      fullPath: '/conversation-starters/$id/'
      preLoaderRoute: typeof ConversationStartersIdIndexRouteImport
      parentRoute: typeof ConversationStartersIdRouteRoute
    }
    '/partner/deals/create': {
      id: '/partner/deals/create'
      path: '/deals/create'
      fullPath: '/partner/deals/create'
      preLoaderRoute: typeof PartnerDealsCreateRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/interests/$id/edit': {
      id: '/interests/$id/edit'
      path: '/edit'
      fullPath: '/interests/$id/edit'
      preLoaderRoute: typeof InterestsIdEditRouteImport
      parentRoute: typeof InterestsIdRouteRoute
    }
    '/conversation-starters/$id/edit': {
      id: '/conversation-starters/$id/edit'
      path: '/edit'
      fullPath: '/conversation-starters/$id/edit'
      preLoaderRoute: typeof ConversationStartersIdEditRouteImport
      parentRoute: typeof ConversationStartersIdRouteRoute
    }
    '/partner/venue/$venueId/edit': {
      id: '/partner/venue/$venueId/edit'
      path: '/venue/$venueId/edit'
      fullPath: '/partner/venue/$venueId/edit'
      preLoaderRoute: typeof PartnerVenueVenueIdEditRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/partner/deals/$dealId/edit': {
      id: '/partner/deals/$dealId/edit'
      path: '/deals/$dealId/edit'
      fullPath: '/partner/deals/$dealId/edit'
      preLoaderRoute: typeof PartnerDealsDealIdEditRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/interests/$id/conversation-starters/create': {
      id: '/interests/$id/conversation-starters/create'
      path: '/conversation-starters/create'
      fullPath: '/interests/$id/conversation-starters/create'
      preLoaderRoute: typeof InterestsIdConversationStartersCreateRouteImport
      parentRoute: typeof InterestsIdRouteRoute
    }
    '/interests/$id/conversation-starters/$starterId': {
      id: '/interests/$id/conversation-starters/$starterId'
      path: '/conversation-starters/$starterId'
      fullPath: '/interests/$id/conversation-starters/$starterId'
      preLoaderRoute: typeof InterestsIdConversationStartersStarterIdRouteRouteImport
      parentRoute: typeof InterestsIdRouteRoute
    }
    '/interests/$id/conversation-starters/$starterId/': {
      id: '/interests/$id/conversation-starters/$starterId/'
      path: '/'
      fullPath: '/interests/$id/conversation-starters/$starterId/'
      preLoaderRoute: typeof InterestsIdConversationStartersStarterIdIndexRouteImport
      parentRoute: typeof InterestsIdConversationStartersStarterIdRouteRoute
    }
    '/interests/$id/conversation-starters/$starterId/edit': {
      id: '/interests/$id/conversation-starters/$starterId/edit'
      path: '/edit'
      fullPath: '/interests/$id/conversation-starters/$starterId/edit'
      preLoaderRoute: typeof InterestsIdConversationStartersStarterIdEditRouteImport
      parentRoute: typeof InterestsIdConversationStartersStarterIdRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ConversationStartersIdRouteRouteChildren {
  ConversationStartersIdEditRoute: typeof ConversationStartersIdEditRoute
  ConversationStartersIdIndexRoute: typeof ConversationStartersIdIndexRoute
}

const ConversationStartersIdRouteRouteChildren: ConversationStartersIdRouteRouteChildren =
  {
    ConversationStartersIdEditRoute: ConversationStartersIdEditRoute,
    ConversationStartersIdIndexRoute: ConversationStartersIdIndexRoute,
  }

const ConversationStartersIdRouteRouteWithChildren =
  ConversationStartersIdRouteRoute._addFileChildren(
    ConversationStartersIdRouteRouteChildren,
  )

interface ConversationStartersRouteRouteChildren {
  ConversationStartersIdRouteRoute: typeof ConversationStartersIdRouteRouteWithChildren
  ConversationStartersCreateRoute: typeof ConversationStartersCreateRoute
  ConversationStartersIndexRoute: typeof ConversationStartersIndexRoute
}

const ConversationStartersRouteRouteChildren: ConversationStartersRouteRouteChildren =
  {
    ConversationStartersIdRouteRoute:
      ConversationStartersIdRouteRouteWithChildren,
    ConversationStartersCreateRoute: ConversationStartersCreateRoute,
    ConversationStartersIndexRoute: ConversationStartersIndexRoute,
  }

const ConversationStartersRouteRouteWithChildren =
  ConversationStartersRouteRoute._addFileChildren(
    ConversationStartersRouteRouteChildren,
  )

interface InterestsIdConversationStartersStarterIdRouteRouteChildren {
  InterestsIdConversationStartersStarterIdEditRoute: typeof InterestsIdConversationStartersStarterIdEditRoute
  InterestsIdConversationStartersStarterIdIndexRoute: typeof InterestsIdConversationStartersStarterIdIndexRoute
}

const InterestsIdConversationStartersStarterIdRouteRouteChildren: InterestsIdConversationStartersStarterIdRouteRouteChildren =
  {
    InterestsIdConversationStartersStarterIdEditRoute:
      InterestsIdConversationStartersStarterIdEditRoute,
    InterestsIdConversationStartersStarterIdIndexRoute:
      InterestsIdConversationStartersStarterIdIndexRoute,
  }

const InterestsIdConversationStartersStarterIdRouteRouteWithChildren =
  InterestsIdConversationStartersStarterIdRouteRoute._addFileChildren(
    InterestsIdConversationStartersStarterIdRouteRouteChildren,
  )

interface InterestsIdRouteRouteChildren {
  InterestsIdEditRoute: typeof InterestsIdEditRoute
  InterestsIdIndexRoute: typeof InterestsIdIndexRoute
  InterestsIdConversationStartersStarterIdRouteRoute: typeof InterestsIdConversationStartersStarterIdRouteRouteWithChildren
  InterestsIdConversationStartersCreateRoute: typeof InterestsIdConversationStartersCreateRoute
}

const InterestsIdRouteRouteChildren: InterestsIdRouteRouteChildren = {
  InterestsIdEditRoute: InterestsIdEditRoute,
  InterestsIdIndexRoute: InterestsIdIndexRoute,
  InterestsIdConversationStartersStarterIdRouteRoute:
    InterestsIdConversationStartersStarterIdRouteRouteWithChildren,
  InterestsIdConversationStartersCreateRoute:
    InterestsIdConversationStartersCreateRoute,
}

const InterestsIdRouteRouteWithChildren =
  InterestsIdRouteRoute._addFileChildren(InterestsIdRouteRouteChildren)

interface InterestsRouteRouteChildren {
  InterestsIdRouteRoute: typeof InterestsIdRouteRouteWithChildren
  InterestsCreateRoute: typeof InterestsCreateRoute
  InterestsIndexRoute: typeof InterestsIndexRoute
}

const InterestsRouteRouteChildren: InterestsRouteRouteChildren = {
  InterestsIdRouteRoute: InterestsIdRouteRouteWithChildren,
  InterestsCreateRoute: InterestsCreateRoute,
  InterestsIndexRoute: InterestsIndexRoute,
}

const InterestsRouteRouteWithChildren = InterestsRouteRoute._addFileChildren(
  InterestsRouteRouteChildren,
)

interface PartnerRouteRouteChildren {
  PartnerIndexRoute: typeof PartnerIndexRoute
  PartnerDealsCreateRoute: typeof PartnerDealsCreateRoute
  PartnerDealsDealIdEditRoute: typeof PartnerDealsDealIdEditRoute
  PartnerVenueVenueIdEditRoute: typeof PartnerVenueVenueIdEditRoute
}

const PartnerRouteRouteChildren: PartnerRouteRouteChildren = {
  PartnerIndexRoute: PartnerIndexRoute,
  PartnerDealsCreateRoute: PartnerDealsCreateRoute,
  PartnerDealsDealIdEditRoute: PartnerDealsDealIdEditRoute,
  PartnerVenueVenueIdEditRoute: PartnerVenueVenueIdEditRoute,
}

const PartnerRouteRouteWithChildren = PartnerRouteRoute._addFileChildren(
  PartnerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ConversationStartersRouteRoute: ConversationStartersRouteRouteWithChildren,
  InterestsRouteRoute: InterestsRouteRouteWithChildren,
  PartnerRouteRoute: PartnerRouteRouteWithChildren,
  authAccountRoute: authAccountRoute,
  authLoginRoute: authLoginRoute,
  authLogoutRoute: authLogoutRoute,
  authRegisterRoute: authRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
